version: '3.8'
services:
  eureka-server:
    image: eureka
    restart: always
    container_name: eureka
    ports:
      - '8761:8761'
    networks:
      - 'dockernetflix-network'
  zuul-service:
    image: zuul
    restart: always
    container_name: zuul
    ports:
      - '7000:7000'
    networks:
      - 'dockernetflix-network'
  greeting-microservice:
    image: greetmicroservice
    restart: always
    container_name: greetmicroservice
    networks:
      - 'dockernetflix-network'
networks:
  dockernetflix-network: